[package]
name = "cedramarket_v6"
version = "1.0.0"
authors = []

[addresses]
marketplace = "_"

[dependencies]
# This points to the official Cedra Framework
CedraFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-framework", rev = "main" }